use_frameworks!

target 'iOSSDK_Example' do
  pod 'DrdshChatSDKTest', :path => '../'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManagerSwift', '6.2.1'
  pod 'Socket.IO-Client-Swift'
end
