use_frameworks!

target 'iOSSDK_Example' do
  pod 'GGiOSSDK'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'MBProgressHUD'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'IQKeyboardManagerSwift', '6.2.1'
  
end
